### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pygmalion-y** [carrois/Kernkraft#20] opened 2020-07-26 11:19 UTC
I get this error message while launch glyphs the second time with this plugin on, the interface of plugin does not show glyph.

Traceback (most recent call last):

  File "~/Library/Application Support/Glyphs/Scripts/vanilla/vanillaBase.py", line 503, in action_
    self.callback(sender)

  File "~/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 1291, in buttonRightCallback
    self.setNeighbourGlyphInEditText(+1)  # next Glyph in Font

  File "~/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 1271, in setNeighbourGlyphInEditText
    self.updateGlyphPreview(otherGlyph)

  File "~/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 1125, in updateGlyphPreview
    self.w.view.layer = self.thisFont.glyphs[glyphName].layers[chosenMasterId]

AttributeError: 'Window' object has no attribute 'view'

App:2.6.5-1342 Plugin:(null)-(null)

**Comment by Mark2Mark** [comment] 2020-07-31 07:46
Does this repeat? Is it still coming?

**Comment by pygmalion-y** [comment] 2020-07-31 07:54
> Does this repeat? Is it still coming?

Yes, it appears once you restart Glyphs. It appears as no glyphs showed up. The way to figure out is seems like leave it couple hours, I tried all the ways might works but doesn't, and all other plugins are turned off.

**Comment by jansindl3r** [comment] 2020-10-09 11:39
Same here... but a bit different 

```The Plugin Kernkraft.glyphsPlugin has caused a crash. Please update it by opening the Plugin Manager or re-downloading it from the original source.
Details:
Traceback (most recent call last):

  File "~/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/plugin.py", line 15, in <module>
    import KernKraftModule as KKM

  File "~/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 37, in <module>
    from vanilla import *

  File "~/Library/Application Support/Glyphs/Scripts/vanilla/__init__.py", line 3, in <module>
    from vanilla.vanillaBrowser import ObjectBrowser

  File "~/Library/Application Support/Glyphs/Scripts/vanilla/vanillaBrowser.py", line 7, in <module>
    from objc import python_method

ImportError: cannot import name python_method

App:2.6.5-1342 Plugin:4-2.0.0```

**Comment by schriftgestalt** [comment] 2020-10-09 13:00
Hi

Please update to the latest cutting edge version and update modules in Preferences > Addons > Modules.

Best
Georg Seifert

**Comment by jansindl3r** [comment] 2020-10-12 10:21
_cutting edge_

**Comment by Mark2Mark** [comment] 2020-10-13 08:31
> cutting edge

?

**Comment by oisatsuki** [comment] 2020-12-20 17:45
Hello, I am having trouble installing and using KernKraft. 
My glyphs is up to date (2.6.5) and I did install vanilla module before instaling kernkraft. When I open the app, this error message shows up: 

"The Plugin Kernkraft.glyphsPlugin has caused a crash. Please update it by opening the Plugin Manager or re-downloading it from the original source.

Details:
Traceback (most recent call last):

  File "~/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/plugin.py", line 15, in <module>
    import KernKraftModule as KKM

  File "~/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 37, in <module>
    from vanilla import *

  File "~/Library/Application Support/Glyphs/Scripts/vanilla/__init__.py", line 3, in <module>
    from vanilla.vanillaBrowser import ObjectBrowser

  File "~/Library/Application Support/Glyphs/Scripts/vanilla/vanillaBrowser.py", line 7, in <module>
    from objc import python_method

ImportError: cannot import name python_method

App:2.6.5-1342 Plugin:4-2.0.0"

What should I do to get it working?

**Comment by oisatsuki** [comment] 2020-12-20 17:46
> Hi Please update to the latest cutting edge version and update modules in Preferences > Addons > Modules. Best Georg Seifert
> […](#)
> Am 09.10.2020 um 13:39 schrieb Jan Šindler ***@***.***>: Same here... but a bit different Details: Traceback (most recent call last): File "~/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/plugin.py", line 15, in <module> import KernKraftModule as KKM File "~/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 37, in <module> from vanilla import * File "~/Library/Application Support/Glyphs/Scripts/vanilla/__init__.py", line 3, in <module> from vanilla.vanillaBrowser import ObjectBrowser File "~/Library/Application Support/Glyphs/Scripts/vanilla/vanillaBrowser.py", line 7, in <module> from objc import python_method ImportError: cannot import name python_method App:2.6.5-1342 Plugin:4-2.0.0``` — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I've already did this and still doesn't work. The error message appears as soon as I open the app and nothing seems to make it work. It's not showing on the Glyphs tab either.

**Comment by schriftgestalt** [comment] 2020-12-20 21:01
The error is caused by a too new version of vanilla. You need the latest version of Glyphs and then update modules as written before. You need at least version 2.6.6-1343. Activate "Show cutting edge versions" in Preferences > Updates and update again. Then reload the modules.

**Comment by oisatsuki** [comment] 2020-12-20 21:49
It worked, thank you!

**Comment by Mark2Mark** [comment] 2021-01-09 22:14
@Mark2Mark referencing [crash report from the Glyphs Forum](https://forum.glyphsapp.com/t/kernkraft-installation-and-instructions-for-use/15430/18) to here

**Comment by Mark2Mark** [comment] 2021-01-25 19:28
Closing. Cannot reproduce, but *could* be fixed already.

**Closed as completed by Mark2Mark** 2021-01-25 19:28 UTC
