### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by schriftgestalt** [carrois/Kernkraft#19] opened 2020-07-17 20:41 UTC
I got this from a user
```
Details:
Traceback (most recent call last):

 File "~/Library/Application Support/Glyphs/Scripts/vanilla/vanillaBase.py", line 503, in action_
   self.callback(sender)

 File "~/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 1146, in masterSelection
   self.updateGlyphPreview(self.w.glyphInput.get())

 File "~/Library/Application Support/Glyphs/Repositories/Kernkraft/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 1157, in updateGlyphPreview
   self.view._layer = self.thisFont.glyphs[glyphName].layers[self.mID] # selected Master from GlyphsApp

AttributeError: 'NoneType' object has no attribute 'layers'

App:2.6.5-1342 Plugin:(null)-(null)
```

**Comment by carrois** [comment] 2020-07-17 21:52
???

**Comment by Mark2Mark** [comment] 2021-01-25 19:28
Closing. Cannot reproduce, but *could* be fixed already.

**Closed as completed by Mark2Mark** 2021-01-25 19:28 UTC
